/**
 * API Tapiceria
 * Documentación Api Tapiceria
 *
 * OpenAPI spec version: v1
 * Contact: maycolguerrero2021@itp.edu.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ComprasTiposMateriales {
    'id'?: number;
    'precio': number;
    'cantidad': number;
    'compra': number;
    'tipoMaterial': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "precio",
            "baseName": "precio",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidad",
            "baseName": "cantidad",
            "type": "number",
            "format": ""
        },
        {
            "name": "compra",
            "baseName": "compra",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoMaterial",
            "baseName": "tipoMaterial",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComprasTiposMateriales.attributeTypeMap;
    }

    public constructor() {
    }
}

