/**
 * API Tapiceria
 * Documentación Api Tapiceria
 *
 * OpenAPI spec version: v1
 * Contact: maycolguerrero2021@itp.edu.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Creditos {
    'id'?: number;
    'totalCredito': number;
    'montoInicial': number;
    'fechaCredito': string;
    'usuario': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalCredito",
            "baseName": "total_credito",
            "type": "number",
            "format": ""
        },
        {
            "name": "montoInicial",
            "baseName": "monto_inicial",
            "type": "number",
            "format": ""
        },
        {
            "name": "fechaCredito",
            "baseName": "fecha_credito",
            "type": "string",
            "format": "date"
        },
        {
            "name": "usuario",
            "baseName": "usuario",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Creditos.attributeTypeMap;
    }

    public constructor() {
    }
}

