/**
 * API Tapiceria
 * Documentación Api Tapiceria
 *
 * OpenAPI spec version: v1
 * Contact: maycolguerrero2021@itp.edu.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DetallesTapizados {
    'id'?: number;
    'cantidadTelasColores'?: number;
    'cantidadTipoMaterial'?: number;
    'tipoTela': number;
    'color': number;
    'producto': number;
    'tipoEspumilla': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidadTelasColores",
            "baseName": "cantidad_telasColores",
            "type": "number",
            "format": ""
        },
        {
            "name": "cantidadTipoMaterial",
            "baseName": "cantidad_tipoMaterial",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoTela",
            "baseName": "tipoTela",
            "type": "number",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "number",
            "format": ""
        },
        {
            "name": "producto",
            "baseName": "producto",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoEspumilla",
            "baseName": "tipoEspumilla",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DetallesTapizados.attributeTypeMap;
    }

    public constructor() {
    }
}

