/**
 * API Tapiceria
 * Documentación Api Tapiceria
 *
 * OpenAPI spec version: v1
 * Contact: maycolguerrero2021@itp.edu.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Pagos {
    'id'?: number;
    'monto': number;
    'fechaPago': string;
    'ventaProducto': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "monto",
            "baseName": "monto",
            "type": "number",
            "format": ""
        },
        {
            "name": "fechaPago",
            "baseName": "fecha_pago",
            "type": "string",
            "format": "date"
        },
        {
            "name": "ventaProducto",
            "baseName": "ventaProducto",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Pagos.attributeTypeMap;
    }

    public constructor() {
    }
}

