/**
 * API Tapiceria
 * Documentación Api Tapiceria
 *
 * OpenAPI spec version: v1
 * Contact: maycolguerrero2021@itp.edu.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Productos {
    'id'?: number;
    'tipoMaterialData'?: string;
    'tipoProductoData'?: string;
    'descripcion'?: string | null;
    'fechaFabricacion'?: string | null;
    'precioCosto': number;
    'precioVenta': number;
    'tipoProducto': number;
    'tipoMaterial': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoMaterialData",
            "baseName": "tipoMaterial_data",
            "type": "string",
            "format": ""
        },
        {
            "name": "tipoProductoData",
            "baseName": "tipoProducto_data",
            "type": "string",
            "format": ""
        },
        {
            "name": "descripcion",
            "baseName": "descripcion",
            "type": "string",
            "format": ""
        },
        {
            "name": "fechaFabricacion",
            "baseName": "fecha_fabricacion",
            "type": "string",
            "format": "date"
        },
        {
            "name": "precioCosto",
            "baseName": "precio_costo",
            "type": "number",
            "format": ""
        },
        {
            "name": "precioVenta",
            "baseName": "precio_venta",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoProducto",
            "baseName": "tipoProducto",
            "type": "number",
            "format": ""
        },
        {
            "name": "tipoMaterial",
            "baseName": "tipoMaterial",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Productos.attributeTypeMap;
    }

    public constructor() {
    }
}

